### ISSUE TITLE
Discussion to define technologies to be used

### ISSUE THREAD

**Issue by karinamelo26** [karinamelo26/fus#3]
# Front-end
- [React](https://reactjs.org/)
- [SASS](https://sass-lang.com/)
- [React Router](https://reactrouter.com/)
- [React Query](https://react-query-v3.tanstack.com/)
- [React Hook Form](https://react-hook-form.com/)
- [MUI Base](https://mui.com/base/getting-started/overview/)

# Back-end
- [NodeJS 18](https://nodejs.org/en/)
- [Electron](https://www.electronjs.org/)
- [Typescript](https://www.typescriptlang.org/)
- [TypeORM](https://typeorm.io/)
- [SQLite](https://www.sqlite.org/index.html)
- [esbuild](https://esbuild.github.io/)

# Both
- [Vite](https://vitejs.dev/)
- [Vitest](https://vitest.dev/)
- [Prettier](https://prettier.io/)
- [ESLint](https://eslint.org/)

**Comment by stLmpp** [comment]
As discussed on 22/07/2022, we decided to use React as the main framework for the front-end and Electron for the back-end
